/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.danielb;

import hu.danielb.components.ButtonEditor;
import hu.danielb.components.ButtonRenderer;
import hu.danielb.data.Database;
import hu.danielb.data.Korosztaly;
import hu.danielb.listeners.EditingStoppedListener;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author balu
 */
public class KorosztalyokDialog extends BaseDialog {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;

    /**
     * Creates new form KorosztalyokDialog
     *
     * @param owner
     */
    public KorosztalyokDialog(Dialog owner) {
        super(owner);
        init();
        this.setLocationRelativeTo(owner);
    }

    public KorosztalyokDialog(Frame owner) {
        super(owner);
        init();
        this.setLocationRelativeTo(owner);
    }

    private void init() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        loadData();
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = evt.getID();
        new AddKorosztalyDialog(this,
                new Korosztaly(Integer.parseInt((String) jTable1.getValueAt(row, 0)),
                        (String) jTable1.getValueAt(row, 1),
                        Integer.parseInt((String) jTable1.getValueAt(row, 2)),
                        Integer.parseInt((String) jTable1.getValueAt(row, 3)))).setVisible(true);
    }

    private void loadData() {
        Vector<Vector<String>> data = new Vector<>();
        try {
            ResultSet rs = Database.runSql("select * from Korosztaly");
            while (rs.next()) {
                data.add(new Vector<>(Arrays.asList(new String[]{String.valueOf(rs.getInt("id")), rs.getString("name"), String.valueOf(rs.getInt("minimum")), String.valueOf(rs.getInt("maximum")), "Szerkeszt"})));
            }
        } catch (SQLException ex) {
            Logger.getLogger(KorosztalyokDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, new Vector<>(Arrays.asList(new String[]{"", "Név", "Alsó határ", "Felső határ", ""}))) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 4;
            }
        });
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
        jTable1.getColumnModel().getColumn(4).setCellEditor(new ButtonEditor(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        }).addEditingStoppedListener(new EditingStoppedListener() {
            @Override
            public void editingStopped() {
                loadData();
            }
        }));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    // End of variables declaration//GEN-END:variables
}
